use clap::ArgAction::SetTrue;
use clap::{Arg, Command, command};

pub fn get_command() -> Command {
    command!().arg(
        Arg::new("output")
            .short('o')
        .long("output")
            .number_of_values(1)
            .required(false)
            .default_value("dface.sqlite")
            .help("Define output file for program to write to. Will create file if name does not exist in working directory. If using a custom filename, ensure it is specified on every run. If not, the name of dface.sqlite will be the default.")
    )
        .arg(Arg::new("verbose")
            .action(SetTrue)
            .short('v')
                 .long("verbose")
                 .help("Enable verbose output")
        )
        .arg(Arg::new("New Monitor")
        .short('n')
            .long("new-monitor")
                 .number_of_values(1)
                 .required(false)
                 .help("Adds new monitor URI to database. Please enter a valid URI, and see the args for new Monitor Frequency, Threshold, and retention as they must be used to create a new monitor") 
        )
        .arg(Arg::new("New Monitor Frequency")
            .short('f')
            .long("new-monitor-frequency")
                 .number_of_values(1)
                 .help("Mandatory if creating new monitor. Provide an integer to specify the number of seconds in between each time this Webpage is checked by the program ")
        )
        .arg(Arg::new("New Monitor Threshold")
        .short('t')
            .long("new-monitor-threshold")
            .number_of_values(1)
                 .help("Mandatory if creating new monitor. Provide an integer representing a similarity value of which you want alerts to trigger AT or BELOW (0 being completely different, and 100 being identical)")
        )
                 .arg(Arg::new("New Monitor Retention")
                 .short('r')
                     .required(false)
                          .long("new-monitor-retention")
                          .number_of_values(1)
                          .help("Mandatory if creating new monitor. Provide an integer to specify the number of seconds the page states, corresponding to the monitor, should be held in the Page table on your database.")
                 )
        .arg(Arg::new("Show hash similarities")
            .action(SetTrue)
        .short('s')
            .long("show-similarities")
                 .help("Prints all URI's recorded similarity from last run")
        )
        .arg(Arg::new("Ignore Frequency")
            .action(SetTrue)
        .short('i')
            .long("ignore-frequency")
                 .help("Ignores all monitor frequency values")
        )
        .arg(Arg::new("Compare Old Page URI")
            .short('c')
            .long("compare-old-page-uri")
            .number_of_values(1)
            .required(false)
                 .help("Outputs a list of previous pages based off of provided uri. Please ensure you've provided a URI currently present in database alongside the -c argument")
        )
        .arg(Arg::new("Show logs")
            .short('l')
                 .long("show-logs")
            .help("Prints all previous logs")
                 .required(false)
                 .action(SetTrue)
        )
}
